name = "stats"
main = "./src/server.js"
compatibility_date="2022-02-26"

account_id = "da445ff826f532cb7d62d370a154c8ec"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# TOKEN
# PUBLIC_KEY
# CLIENT_ID
# GUILD_ID
